name: 'Deployment statistics for Propelo'
description: 'Prepare and submit deployment/release statistics to Propelo (levelops.io)'
inputs:
  github_repository:
    description: 'Github Repository'
    required: true
  commit_sha:
    description: 'Commit SHA'
    required: true
  release_tag:
    description: 'Release TAG'
    required: true
  environment:
    description: 'Deployment environment'
    required: true
  github_user:
    description: 'Github user'
    required: true
  github_token:
    description: 'Github Token'
    required: true
  propelo_token:
    description: 'Propelo Token'
    required: true
  propelo_deployment_instance_guid:
    description: 'Propelo jenkins_instance_guid predefined variable'
    required: true

branding:
  icon: 'trending-up'  
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - id: debug
      shell: bash
      run: |
        echo Current folder is $(pwd)
        echo ls current folde $(ls -alh)
        echo value of GITHUB_ACTION_PATH env var $GITHUB_ACTION_PATH
        echo ls GITHUB_ACTION_PATH $(ls -alh $GITHUB_ACTION_PATH)
        echo reqierements file $(ls -alh $GITHUB_ACTION_PATH/requirements.txt)
        echo output of GITHUB_ACTION_PATH/requirements.txt $(cat $GITHUB_ACTION_PATH/requirements.txt)

    # - uses: actions/setup-python@v4
    #   id: setup_python
    #   with:
    #     python-version: 3.8
    #     cache: 'pip'
    # ! ${{ steps.setup.outputs.python-path }}

    - id: install_requirements
      shell: bash
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
    
    - id: execute_python_script
      shell: bash
      run: |
          python3 $GITHUB_ACTION_PATH/propelo.py
      env:
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        ENVIRONMENT: ${{ inputs.environment }}
        GITHUB_USER: ${{ inputs.github_user }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PROPELO_TOKEN: ${{ inputs.propelo_token }}
        PROPELO_GUID: ${{ inputs.propelo_deployment_instance_guid }}
